#  Stage 1: Build 
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY ./cheko-app .
RUN npm run build

# Stage 2: Serve via Nginx
FROM nginx:alpine AS runtime

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
