version: "3.8"

services:
  Frontend:
    build: ./Frontend
    container_name: Frontend
    ports:
      - "80:80"
    depends_on:
      - Backend
    environment:
      - REACT_APP_API_URL=http://cheko.fae.sale

  Backend:
    build: ./Backend
    container_name: Backend
    ports:
      - "8080:8080"
    depends_on:
      - DB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DB:5432/restaurant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=test

  DB:
    build: ./DB
    container_name: postgres17-postgis
    environment:
      - POSTGRES_DB=restaurant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
